apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: ec2
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  path: ./infrastructure/aws/ec2
  sourceRef:
    kind: GitRepository
    name: flux-system
