apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: ec2
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  destroyResourcesOnDeletion: true
  path: ./infrastructure/aws/ec2
  sourceRef:
    kind: GitRepository
    name: flux-system
  varsFrom:
    - kind: Secret
      name: aws-creds
      varsKeys:
        - aws_access_key_id
        - aws_secret_access_key
